Ai no timers
lulebe/jscrusades pull request #12
Opened 2022-04-19 23:43 UTC by lulebe

Removed timers from AI code.

2022-04-19 23:45 UTC, lulebe commented
BTW, only the last 2 commits are relevant. Everything else is the same as initial_ai_integration. Not sure if Github understands that as soon as you review and merge that one, this one will only be 2 commits ahead of master. But anyway, just ignore everything before that.

2022-04-22 18:42 UTC, Simsso requested changes
One counter increment to check, other than that slim and nice upgrade! Especially the long switch deserves a laudatio!

2022-04-22 18:42 UTC, Simsso commented on static/js/gamedata/ai.js
> +  } while (turnResult > 0)
Add comment "first do-while loop".

2022-04-22 18:42 UTC, Simsso commented on static/js/gamedata/legacy/ai.js
>  export function startLegacyAi (game, endTurnCallback) {
`endTurnCallback` unused?

2022-04-22 18:42 UTC, Simsso commented on static/js/gamedata/ai.js
> +  const makeTurn = startLegacyAi(game)
`executeSubTurn`?

2022-04-22 18:42 UTC, Simsso commented on static/js/gamedata/legacy/ai.js
> +      return false;
Return didFight?

2022-04-22 18:42 UTC, Simsso commented on static/js/gamedata/legacy/ai.js
> +         UnitCounter++;
What if the enemy unit died? Would we skip one?

2022-04-22 18:42 UTC, Simsso commented on static/js/gamedata/legacy/ai.js
> +         UnitCounter++;
Or have index out of bounds in `const unit = compat.World.unitList[UnitCounter];`

2022-04-22 20:27 UTC, Simsso approved these changes

2022-04-22 20:27 UTC, Simsso commented on static/js/gamedata/legacy/ai.js
> +      return false;
Nope.

2022-04-22 20:28 UTC, merged